### ISSUE TITLE
Get rid of the sharp library

### ISSUE THREAD

**Issue by Noir-** [Lange/node-elgato-stream-deck#61] opened 2018-12-15 22:31 UTC
Please consider leaving the image conversion functionality to the host application.

Depending on the user environment this introduces a **lot** of complexity to get it running.

For example, I want to use this on a Raspberry Pi. When running npm install everything seems fine but on runtime it turns out that sharp was not even built. In order to build it, a library (libvips) must be installed. After that the build seems to succeed but at runtime another error pops up complaining `ZLIB_1.2.9' not found` which seems to be a dependency of `libpng16`. However, Raspbian (aka Debian Stretch) only ships zlib 1.2.8 so I would have to hack this somehow into the system (which could break something else) or even build it by myself and hack it into the sharp lib (which could break all future lib updates).

But I don't even tried for now. I don't know if this would be the thing which would make everything work or if there's another surprise waiting.

Instead I'm writing this ticket in the hope to aid this dependency hell.

I suggest that the corresponding method is deprecated/removed in future releases and a simple example which utilizes the plain `write(buffer)` method in conjunction with sharp is added to the readme and example code.

**Comment by idoodler** [comment] 2019-01-01 02:21
I would also favor this change.

**Comment by Julusian** [comment] 2019-05-29 21:22
This has been done and will be in the next release

**Closed by Julusian** 2019-05-29 21:22 UTC

**Comment by scottopherson** [comment] 2020-03-04 23:53
@Julusian is there an example somewhere that doesn't utilize sharp?

**Comment by Julusian** [comment] 2020-03-05 12:23
@scottopherson not really. All of the examples here are based around loading in a png, so it is much simpler to use sharp.
But you simply give fillImage a raw rgb buffer of the correct size, which can come from anything, not only sharp.

**Comment by ventr1x** [comment] 2020-03-18 11:05
Well, not really as sharp does some very weird magic behind the scenes with the buffer length.
Any other, including ImageMagick, library would not give you a static buffer size back.
Sharp even returns different sizes depending on e.g. alpha channel. It returns different sizes even depending on image type.
It's an absoule mess to work with this.

I tried ImageMagick, gm, Jimp.. none of these work with this plugin.

**Comment by Julusian** [comment] 2020-03-18 11:31
@ventr1x I find it strange that they would give back weird length buffers for binary pixel data. And as for alpha, this library expects rgb data without an alpha channel.

I am very open to extending the api to do what you need, this simply hasn't been raised as a problem before. And I have only used sharp myself, so it has always just worked. Could you suggest how the api should look to cover what you need? 
Perhaps an extra parameter to fillImage which looks like:
```
{
	format: 'rgb' | 'bgr' | 'rgbx' | 'bgrx', // default 'rgb'
	stride?: number, // default to no gap between rows
	rotation?: 'normal' | 'cw' | 'ccw' | '180' // default 'normal'
}
```

I am guessing as to what would be needed to make this flexible enough. As we are already doing pixel manipulation to do a horizontal flip, and possibly a rgb to bgr conversion, this shouldn't have any performance impact. Technically we are already doing the stride part of this internally to minimise on copies when fillPanel is used.

And if the image isnt large enough we could still throw an error, I think those numbers should make it possible to check that, but with no upper limit on size.

**Comment by ventr1x** [comment] 2020-03-18 12:31
Basically Jimp toBuffer method returns a buffer length depending on image filesize.
Using the bitmap data from Jimp returns the buffer length sharp would WITH alpha channel - even if you use jpg/rgb images. That is obviously a bug/issue with Jimp as that plugin also has no flatten() method at all.
I raised a feature request with them for it.

Sharp is inconvenient as it's over 60MB big and can't be packed into an exe with e.g. pkg. It also doesn't support most, if not all, microprocessors.

But I'd say the issue is more with the image processing plugins than Streamdeck. It's just a bit problematic that there is no example besides sharp. 
As Jimp is javascript only, it would be my preferable way in many use cases (I abuse Streamdeck as a remote control panel for PLCs; that software often runs on raspberry or even less capable devices).
