### ISSUE TITLE
Color issue fillImage

### ISSUE THREAD

**Issue by numri** [Lange/node-elgato-stream-deck#29] opened 2017-05-26 18:12 UTC
Hi guys!

The streamdecks display seem to output BGR, not RGB, to amend this i threw around the colors in the buffer like below, not sure if it was the best way about it, but it works:

```
sharp(path.resolve(__dirname, 'github_logo.png'))
	.flatten()
	.resize(streamDeck.ICON_SIZE, streamDeck.ICON_SIZE)
	.raw()
	.toBuffer(function(err,buffer,info) {
		//Reorganize buffer from RGB to BGR to match streamdeck display
		for(i = 0 ; i < buffer.length; i=i+3) {
		var r = buffer.readUInt8(i),
		g = buffer.readUInt8(i+1),
		b = buffer.readUInt8(i+2);

		buffer.writeUInt8(b, i);
		buffer.writeUInt8(g, i+1);
		buffer.writeUInt8(r, i+2);
	};
```

**Comment by Lange** [comment] 2017-05-26 18:20
Hi @numri!

You are correct that the stream deck does indeed use BGR and not RGB. However, our code already accounts for this: [index.js#L147](https://github.com/Lange/node-elgato-stream-deck/blob/master/index.js#L147)

I've just double checked our code by running [`examples/fill-button-when-pressed.js`](https://github.com/Lange/node-elgato-stream-deck/blob/master/examples/fill-button-when-pressed.js), and it does indeed seem to be working as intended.

Was this code not behaving as expected for you? What code did you write that resulted in this unexpected behavior?

**Comment by Lange** [comment] 2017-05-26 18:22
Actually, scratch that. You're right! That's what I get for testing this with a black and white image haha. I just tried it out with a color image and we do indeed have an error. We'll work on it shortly.

**Comment by numri** [comment] 2017-05-26 18:27
Sorry, I'm new to github so I must have missed that example, i tried the one on the "main page"..  Glad to contribute! 👍

**Comment by Lange** [comment] 2017-05-26 18:35
This should be fixed now. Thanks for the heads up!

**Closed** 2017-05-26 18:34 UTC
Labels: bug
